apiVersion: v1
kind: Pod
metadata:
  name: online-inference-health
  labels:
    app: online-inference-health
spec:
  containers:
    - image: alinazemlev/online_inference:v2
      name: online-inference-health
      imagePullPolicy: Always
      ports:
        - containerPort: 80
      readinessProbe:
        httpGet:
          path: /healthz
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 3
      livenessProbe:
        httpGet:
          path: /live
          port: 80
        initialDelaySeconds: 45
        periodSeconds: 10
