class_params:
  alpha: 0.0001
  loss: hinge
  max_iter: 10000
  penalty: l2
  type: LogisticRegression
  type_save: probs
features_params:
  binary_cols:
  - fbs
  - exang
  - sex
  categorical_cols: []
  numerical_cols:
  - oldpeak
  - slope
  - ca
  - restecg
  - chol
  - trestbps
  - cp
  - thal
  - thalach
  - age
  target_col: target
input_data_path: ml_project/data/raw/test.csv
metric_path: ml_project/models/metrics.json
models_params:
  categorical_vectorizer_path: ml_project/models/dv_x.pkl
  classifier_path_postfix: ml_project/models/classifier.pkl
  fill_empty: -111
  imputer_path: ml_project/models/imputer.pkl
  scaling_path: ml_project/models/scaler.pkl
params_for_save:
  path_to_save: configs/predict_config_sgd.yaml
prediction_path: ml_project/predict/prediction.csv
